### PR TITLE
Parse passwords with special chars correctly

### PR DESCRIPTION
**Pull request by pm-trey**
What:
Could not connect to Postgresql DBs using passwords with special characters.

Fix:
Implement url decoding for password passed to Postgresql config

Tests:
Passing

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]

**Comment by agirling** [comment]
+1

Thank you for proposing this PR @pm-trey.

My use case involves AWS RDS IAM authentication against postgres, and special characters in the password has been the limiting factor.

**Comment by pepoviola** [comment]
Ping @evoxmusic, I thinks this is a good one to merge.
Thx!

**Comment by wfclark5** [comment]
@pepoviola just wondering when this one will be merged?

**Comment by pepoviola** [comment]
Ping @evoxmusic, can you merge this one? Thanks!!

**Review by evoxmusic — APPROVED** [review]

**Comment by wfclark5** [comment]
Thank you @evoxmusic @pepoviola

**Pull request merged**
