### PR TITLE
feat: mongo source

### PR DESCRIPTION
**Pull request by benny-n**
- [x] support mongo connection uri in config
 - [x] add mongo service docker-compose
 - [x] create boilerplate for mongo `Source`
 - [x] implement recursive transform (specific for mongo)
 - [x] implement mongo dump-parser
 - [x] integrate dump-parser in `read_and_transform`
 - [x] add tests for everything

### CODE REVIEW

**Comment by benny-n** [comment]
Hi guys, how should we handle a db with multiple collections? 
When using mongodump, by default, the dump goes to `./dump/<db_name>/`
We can call mongodump with `--out "-"` for the dump to go to stdout, but mongodump can only dump a **single** collection to stdout. Should we run more than one `Command` or not use stdout at all and read everything from `./dump/<db_name>/`?

**Comment by evoxmusic** [comment]
Hey @benny-n 👋 it's better to stream the content on stdout and run multiple times the commands to dump all the collections.

Why not dump on disk? Because RepliByte must run in a stateless environment and must be able to handle even 1TB of data without having 1TB of disk. 

Future improvement: it's possible that RepliByte is not fast enough to keep a low memory footprint while handling the data from stdout. A long term solution would be to use the local disk as a buffer.

**Comment by benny-n** [comment]
I'm glad to announce that mongo as source feature is pretty much complete :)
now all that's left is to add mongo as destination and test replibyte with mongo!
should implementation of mongo as destination be in a different PR?
if so, I think this draft is ready for review.
@evoxmusic let me know how to procceed.

**Comment by evoxmusic** [comment]
Well done @benny-n 💪💪 huge work. I take a look in a few hours

**Comment by evoxmusic** [comment]
@benny-n I reviewed your PR and I have nothing to say. It's super clean! I can merge it now from my POV. Maybe the only thing would be to rename `Mongo` into `MongoDB` for the crate and struct names.

Do you plan to work on the `destination/mongodb.rs` in a second PR?

**Comment by benny-n** [comment]
@evoxmusic Thanks!
I will rename the struct like you suggested, 
and yes, I plan to work on destination/mongodb.rs in a second PR 🙂

**Pull request merged**
