### PR TITLE
fix: Add utf-8 parsing error handling

### LINKED ISSUE #220: Utf8Error on dump create
Database: **MariaDB**
Version: **10.5.15**
Character set: **Utf8mb4**

Command ```cat dump.sql | replibyte -c replibyte.yaml dump create -i -s mysql``` return this error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 950246712, error_len: Some(1) }', /root/src/dump-parser/src/utils.rs:74:70
```

Dump Command: 
```
mysqldump -h XXX -u XXX -p --add-drop-database --add-drop-table --skip-extended-insert --complete-insert --single-transaction --quick --column-statistics=0 --default-character-set=utf8mb4 db > dump.sql
```

- I tried dump with `--default-character-set=utf8` and i got the same error.
- I tried with and without transformer and i got the same error.

### PR DESCRIPTION
**Pull request by sondrelg**
Fixes #220

Utf-8 parse errors affect users, and given the choice between panicking and skipping a query, the latter seems like the better option.

There might be a third option I'm not seeing though. Let me know if you prefer to solve this another way 👍

### CODE REVIEW

**Comment by sondrelg** [comment]
I see there's no `log` crate in the `dump-parser` module. Should I:
- remove the logger,
- replace it with println, or 
- add `log`?

**Comment by evoxmusic** [comment]
FYI tests are failing

**Comment by sondrelg** [comment]
Thanks @evoxmusic, I'm aware 👍 Please see my last comment - the tests are failing because I wasn't sure how to implement the fix, and I added a warning logger without the necessary crate.

Would you prefer some output when `continue`'ing, or no output?

**Comment by sondrelg** [comment]
Removed the logger for now 👍

**Comment by sondrelg** [comment]
Any chance of reviewing this @evoxmusic :bow:

**Review by evoxmusic — APPROVED** [review]

**Pull request merged**
