### PR TITLE
Release v0.8.1

### PR DESCRIPTION
**Pull request by evoxmusic**
Signed-off-by: Romaric Philogène <rphilogene@qovery.com>

cc @fabriceclementz 👍🏽

### CODE REVIEW

**Comment by evoxmusic** [comment]
Argh, the update as commit some files that I didn't want to commit 😂 - I need to revert those changes

**Comment by fabriceclementz** [comment]
@evoxmusic 
I'm not sure why there is already a 0.8.1 release here https://github.com/Qovery/Replibyte/releases/tag/v0.8.1 as the PR isn't merged ?

**Comment by evoxmusic** [comment]
Not sure as well what happened. What I did is:

1. I've been in the main branch
2. I executed the script `./release.sh 0.7.3 0.8.1`
3. That's it.

Did I miss something?

**Comment by fabriceclementz** [comment]
No, it's all good. I will retry it  on a fake repo

**Comment by fabriceclementz** [comment]
I understood what happened. 
It's necessary to wait for the PR is merged before validating the last step of the release script.
You can see how this final step works here: https://github.com/Qovery/Replibyte/blob/main/release.sh#L70
After you merge the PR, it will create properly the Release by running:

```sh
git checkout main
git pull
git tag -a -m"Release v${new}" "v${new}"
git push --tags
```

If we don't wait before the PR is merged, it will use the current state of main without the version bump.

**Pull request merged**
