### PR TITLE
Feat add delete backup command

### LINKED ISSUE #66: Provide a delete backup command
Hi @evoxmusic 

Over the time, more and more backups adds up on the bridge so I think that would be good to have a command to delete a backup from the bridge. This is the signature I propose : 

```sh
replibyte -c "config.yml" backup delete "backup-name-here"
```

In the future we could add options to delete backups like `--older-than=14d` or so.

WDYT?

### PR DESCRIPTION
**Pull request by fabriceclementz**
This PR starts to implement the delete backup command as discussed in #66.

I need to update the readme too and I will update the PR to add the following options: 
- [x] `--older-than=2d` option
- [x] `--keep-last=10` option

Closes #66

### CODE REVIEW

**Comment by fabriceclementz** [comment]
FYI, I just needs to validate arguments, there is only 3 possibilities which are valid:

- backup name and no options
- older-than option only
- keep-last option only

I'll take a look asap

**Comment by fabriceclementz** [comment]
@evoxmusic This PR is ready to merge!

**Comment by fabriceclementz** [comment]
@evoxmusic the conflict is coming from the Readme content which have been moved to the new website.

As it seems you're working on it, how do you prefer I proceed?
Can I add a new section `Delete a dataset` in guides which contains the documentation for the `backup delete` command or it should be moved in another section of the website?

**Comment by evoxmusic** [comment]
Absolutely @fabriceclementz - feel free to complete the documentation. You have the instruction in the README.md on how to test in local

**Comment by fabriceclementz** [comment]
Done @evoxmusic !

**Comment by evoxmusic** [comment]
You're the best 🎉

**Pull request merged**
